name: GitAutomator image build test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3

      - name: Set Up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        run: |
          set -x
          docker buildx build --platform linux/amd64 -t cesign/gitautomator:latest -f Dockerfile --load ./
