name: GitAutomator image build and push

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true

    steps:
    - uses: actions/checkout@v3

    - name: Set Up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: GitAutomator - build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: Dockerfile
        platforms: |
          linux/amd64
        push: true
        tags: cesign/gitautomator:latest
